### ISSUE TITLE
Options disabled in Mac?

### ISSUE THREAD

**Issue by MikeKimCR** [benletchford/chrome-tab-cycler#1]
On Mac, clicking Tab Cycler pulls down:

Tab Cycler
Options <--- greyed out
Remove from Chrome...
Hide in Chrome Menu
Manage Extensions

Can you verify that Options is disabled because I'm on Mac?

**Comment by benletchford** [comment]
Hi Mike,

Sorry for the delay. This extension has no options so all operating systems will show that same disabled options menu.

You can, however configure the keyboard shortcuts from Settings -> Extensions -> (At the bottom) Keyboard Shortcuts.

Also on MAC you can cycle tabs with option+command anyway, so this extension may not be super useful in this case.

**Comment by MikeKimCR** [comment]
ctrl+tab works on Macs, it turns out, so yeah. Thanks!

**Comment by benletchford** [comment]
Ctrl+Tab works across all operating systems. Btw, Ctrl+Shift+Tab cycles tabs backward on all operating systems as well!
